name: Daily Build Test Innersource (Ascend NPU)

on:
  schedule:
    - cron: "0 */6 * * *" # Trigger the daily build pipeline every 6 hours.
  push:
    branches:
      - main
    paths:
      - "python/sglang/version.py"
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/daily-build-test-npu-innersource.yml"

concurrency:
  group: daily-build-test-npu-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'Ascend/sglang'
    uses: ./.github/workflows/release-docker-ascend-nightly-innersource.yml
    secrets: inherit

  build-test-1-ascend-npu:
    needs: [ build ]
    if: ${{ needs.build.result == 'success' && (github.repository == 'Ascend/sglang' || github.event_name == 'pull_request') }}
    runs-on: linux-aarch64-a3-2
    container:
      image: ${{ vars.REGISTRY_HK }}/base_image/ascend-ci/sglang:main
    steps:
      - name: Pre-config git access token
        run: |
          # as we use a proxy but checkout@v4 only set basic auth header for github.com
          # so we set the extraheader manually
          TOKEN=`echo -n "x-access-token:${{ secrets.ADMIN_PAT }}"|base64`
          git config --global http.https://gh-proxy.test.osinfra.cn/.extraheader "AUTHORIZATION: basic $TOKEN"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy dataset  # Copy the test dataset to the shared directory
        run: |
          # copy required file from our daily cache
          cp ~/.cache/modelscope/hub/datasets/otavia/ShareGPT_Vicuna_unfiltered/ShareGPT_V3_unfiltered_cleaned_split.json /tmp
          # copy download through proxy
          curl -o /tmp/test.jsonl -L https://gh-proxy.test.osinfra.cn/https://raw.githubusercontent.com/openai/grade-school-math/master/grade_school_math/data/test.jsonl

      - name: Run test
        timeout-minutes: 60
        env:
          SGLANG_USE_MODELSCOPE: true
          SGLANG_IS_IN_CI: true
          HF_ENDPOINT: https://hf-mirror.com
          TORCH_EXTENSIONS_DIR: /tmp/torch_extensions
          STREAMS_PER_DEVICE: 32
        run: |
          cd test/srt
          python3 run_suite.py --suite per-commit-1-ascend-npu --timeout-per-file 3600

  build-test-2-ascend-npu:
    needs: [ build ]
    if: ${{ needs.build.result == 'success' && (github.repository == 'Ascend/sglang' || github.event_name == 'pull_request') }}
    runs-on: linux-aarch64-a3-4
    strategy:
      fail-fast: false
      matrix:
        part: [0, 1]
    container:
      image: ${{ vars.REGISTRY_HK }}/base_image/ascend-ci/sglang:main
    steps:
      - name: Pre-config git access token
        run: |
          # as we use a proxy but checkout@v4 only set basic auth header for github.com
          # so we set the extraheader manually
          TOKEN=`echo -n "x-access-token:${{ secrets.ADMIN_PAT }}"|base64`
          git config --global http.https://gh-proxy.test.osinfra.cn/.extraheader "AUTHORIZATION: basic $TOKEN"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy dataset
        run: |
          # copy required file from our daily cache
          cp ~/.cache/modelscope/hub/datasets/otavia/ShareGPT_Vicuna_unfiltered/ShareGPT_V3_unfiltered_cleaned_split.json /tmp
          # copy download through proxy
          curl -o /tmp/test.jsonl -L https://gh-proxy.test.osinfra.cn/https://raw.githubusercontent.com/openai/grade-school-math/master/grade_school_math/data/test.jsonl

      - name: Run test
        timeout-minutes: 60
        env:
          SGLANG_USE_MODELSCOPE: true
          SGLANG_IS_IN_CI: true
          HF_ENDPOINT: https://hf-mirror.com
          TORCH_EXTENSIONS_DIR: /tmp/torch_extensions
          STREAMS_PER_DEVICE: 32
        run: |
          cd test/srt
          python3 run_suite.py --suite per-commit-2-ascend-npu --timeout-per-file 3600 --auto-partition-id ${{ matrix.part }} --auto-partition-size 2

  build-test-4-ascend-npu:
    needs: [ build ]
    if: ${{ needs.build.result == 'success' && (github.repository == 'Ascend/sglang' || github.event_name == 'pull_request') }}
    runs-on: linux-aarch64-a3-8
    container:
      image: ${{ vars.REGISTRY_HK }}/base_image/ascend-ci/sglang:main
    steps:
      - name: Pre-config git access token
        run: |
          # as we use a proxy but checkout@v4 only set basic auth header for github.com
          # so we set the extraheader manually
          TOKEN=`echo -n "x-access-token:${{ secrets.ADMIN_PAT }}"|base64`
          git config --global http.https://gh-proxy.test.osinfra.cn/.extraheader "AUTHORIZATION: basic $TOKEN"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy dataset
        run: |
          # copy required file from our daily cache
          cp ~/.cache/modelscope/hub/datasets/otavia/ShareGPT_Vicuna_unfiltered/ShareGPT_V3_unfiltered_cleaned_split.json /tmp
          # copy download through proxy
          curl -o /tmp/test.jsonl -L https://gh-proxy.test.osinfra.cn/https://raw.githubusercontent.com/openai/grade-school-math/master/grade_school_math/data/test.jsonl

      - name: Run test
        timeout-minutes: 30
        env:
          SGLANG_USE_MODELSCOPE: true
          SGLANG_IS_IN_CI: true
          HF_ENDPOINT: https://hf-mirror.com
          TORCH_EXTENSIONS_DIR: /tmp/torch_extensions
          STREAMS_PER_DEVICE: 32
          ASCEND_LAUNCH_BLOCKING: 1
        run: |
          pip uninstall -y sglang
          pip install -v -e python[srt_npu] --no-cache-dir
          cd test/srt
          python3 run_suite.py --suite per-commit-4-ascend-npu --timeout-per-file 3600

  bulid-test-npu-finish:
    if: always()
    needs:
      - build-test-1-ascend-npu
      - build-test-2-ascend-npu
      - build-test-4-ascend-npu
    runs-on: ubuntu-latest
    steps:
      - name: Check all dependent job statuses
        run: |
          results=(${{ join(needs.*.result, ' ') }})
          for result in "${results[@]}"; do
            if [ "$result" = "failure" ] || [ "$result" = "cancelled" ]; then
              echo "Job failed with result: $result"
              exit 1
            fi
          done
          echo "All jobs completed successfully"
          exit 0
