name: nightly dev image build and push

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 18 * * *" # run at 2:00AM in TZ=Asia/Shanghai
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/release-docker-ascend-nightly.yml"
      - "python/**"
      - "docker/Dockerfile.npu"

concurrency:
  group: release-docker-ascend-nightly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted-arm64
    strategy:
      matrix:
        cann_version: ["8.2.rc1"]
        device_type: ["a3"]
    steps:
      - name: Checkout repository
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.ADMIN_PAT }}

      - name: Checkout no repository
        if: github.event.pull_request.head.repo.full_name != github.repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.REGISTRY }}/base_image/ascend-ci/sglang
          # push with schedule event
          # push with workflow_dispatch event
          tags: |
            type=ref,event=pr,suffix=-{{sha}}
            type=ref,event=branch
            type=schedule,pattern=main-{{date 'YYYYMMDD'}}
            type=schedule,pattern={{branch}}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: ${{ github.repository == 'Ascend/sglang' && github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.npu
          # TODO: need add x86 platforms support when memfabric ready
          platforms: linux/arm64
          push: ${{ github.repository == 'Ascend/sglang' && github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          provenance: false
          build-args: |
            CANN_VERSION=${{ matrix.cann_version }}
            DEVICE_TYPE=${{ matrix.device_type }}
            REGISTRY=swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci
            PIP_INDEX_URL=https://mirrors.huaweicloud.com/repository/pypi/simple
            APTMIRROR=mirrors.huaweicloud.com
