name: sync datasets and models to our persistent storage
on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/pre-downloaded-datasets.ini"
      - ".github/workflows/pre-downloaded-models.ini"
      - ".github/workflows/sync-models-datasets.ini"
jobs:
  sync_dataset:
    runs-on: linux-aarch64-a3-2
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.2.rc1-910b-ubuntu22.04-py3.11
    steps:
      - uses: actions/checkout@v4
      - name: download models
        run: |
          pip config set global.index-url https://mirrors.huaweicloud.com/repository/pypi/simple
          pip install filelock modelscope
          for m in `cat .github/workflows/pre-downloaded-models.ini`;do modelscope download  --model $m;done
      - name: download dataset
        run: |
          for m in `cat .github/workflows/pre-downloaded-datasets.ini`;do modelscope download  --dataset $m;done
